
mentions: search(query: "repo:wesleybowman/godoist mentions:wesleybowman sort:updated-desc updated:>=2018-12-02", type: ISSUE, first: 100) {
    pageInfo {
        hasNextPage
    }
    edges {
        node {
            __typename
            ... on Issue {
                title
                bodyText
                updatedAt
                url
                comments(first: 100) {
                    totalCount
                    edges {
                        node {
                            body
                            createdAt
                            updatedAt
                            url
                            author {
                                login
                            }
                        }
                    }
                }
            }

            ... on PullRequest {
                title
                bodyText
                updatedAt
                url
                comments(first: 100) {
                    totalCount
                    edges {
                        node {
                            body
                            createdAt
                            updatedAt
                            url
                            author {
                                login
                            }
                        }
                    }
                }
            }
        }
    }
}