
requested_reviews: search(query: $requested_reviews_query_string, type: ISSUE, first: 100) {
    issueCount
    pageInfo {
        endCursor
        startCursor
    }
    edges {
        node {
            ... on PullRequest {
                repository {
                    nameWithOwner
                }
                number
                url
                author {
                    login
                }
                title
                updatedAt
            }
        }
    }
}
